// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ9uxUHojVDLUkmuhN8y4cThKwZXBNfn4',
    appId: '1:1093621480113:web:367a8de20a73726a9ec090',
    messagingSenderId: '1093621480113',
    projectId: 'nutriscan-23add',
    authDomain: 'nutriscan-23add.firebaseapp.com',
    storageBucket: 'nutriscan-23add.appspot.com',
    measurementId: 'G-VRFE7HCS7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-N9w3H0KlbrXme9puhuMLA4L70-J5SE',
    appId: '1:1093621480113:android:e76a1db34a1fb4049ec090',
    messagingSenderId: '1093621480113',
    projectId: 'nutriscan-23add',
    storageBucket: 'nutriscan-23add.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZx6z1Va7yy6-cpl7TFueZbFhJWI_nzw',
    appId: '1:1093621480113:ios:6a09c6fd313cee9d9ec090',
    messagingSenderId: '1093621480113',
    projectId: 'nutriscan-23add',
    storageBucket: 'nutriscan-23add.appspot.com',
    iosBundleId: 'com.example.nutriscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZx6z1Va7yy6-cpl7TFueZbFhJWI_nzw',
    appId: '1:1093621480113:ios:8b05a4f8fb2af4d59ec090',
    messagingSenderId: '1093621480113',
    projectId: 'nutriscan-23add',
    storageBucket: 'nutriscan-23add.appspot.com',
    iosBundleId: 'com.example.nutriscan.RunnerTests',
  );
}

